spring:
  application:
    name: iban_back
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    hikari:
      username: iban
      password: iban

openiban:
  url: https://openiban.com/

server:
  servlet:
    context-path: /api

