spring:
  application:
    name: iban_back
  http:
    codecs:
      log-request-details: true

openiban:
  url: https://openiban.com/

server:
  servlet:
    context-path: /api

logging:
  level:
    # Replace 'com.your.package.OpenIbanClient' with the actual package path to your Feign client interface
    gs.iban_back.web.openiban.OpenIbanClient: DEBUG

feign:
  client:
    config:
      # 'openiban' is the name from @FeignClient(name = "openiban")
      openiban:
        loggerLevel: full